name: 'Unit Tests, Coverage & Sonar'

on:
  workflow_dispatch:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: 'Unit Tests, Coverage & Sonar'
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # 2.35.5
        with:
          php-version: '8.2'
          tools: composer, pecl, phpcs
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Execute linting
        run: |
          make lint-ci

      - name: Create .env file from secrets
        uses: SpicyPizza/create-envfile@ace6d4f5d7802b600276c23ca417e669f1a06f6f # v2.0.3
        with:
          envkey_DATAPLANE_URL: 'hosted.rudderlabs.com'
          envkey_WRITE_KEY: '123456'
          envkey_CONSUMER: 'fork_curl'
          envkey_SSL: false

      - name: Execute unit tests
        run: |
          make tests

      - name: Validate composer.json
        run: |
          composer validate

      - name: Upload reports
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Reports
          path: |
            build/logs    

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
